symedit_api_user:
    pattern: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.user:indexAction
        _sylius:
            sorting:
                username: asc

symedit_api_user_create:
    pattern: /
    methods: [POST]
    defaults:
        _controller: symedit.controller.user:createAction

symedit_api_user_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: symedit.controller.user:showAction

symedit_api_user_update:
    pattern: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: symedit.controller.user:updateAction
